# .github/workflows/include-npm-steps.yml

name: Reusable Node.js Steps

on:
  workflow_call:  # This makes the workflow reusable
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
