# .github/workflows/include-npm-steps.yml
name: Include NPM Steps

on:
  workflow_call:  # Make this workflow reusable
    inputs:
      node_version:
        description: 'Node.js version'
        required: true
        default: '16'

jobs:
  npm-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install
      # Step 4: Run tests
      - name: Run tests
        run: npm test -- --ci --reporters=jest-junit  # Modify if using a different testing framework

      # Step 5: Build the React app
      - name: Build React app
        run: npm run build

      # Optional: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: build/  # Path to the build folder
