name: Main Workflow

on:
  # Customize these events as needed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: react-with-cicd/.github/workflows/node.js.yml@main  # Path to reusable workflow