name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Call reusable Node.js setup workflow
      uses: ./.github/workflows/node.js.yml
      with:
        node-version: ${{ matrix.node-version }}