name: Main Workflow

on:
  # Customize these events as needed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/HaiderAli532/react-with-cicd/blob/main/.github/workflows/node.js.yml@main
