# .github/workflows/nodejs.yaml
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    # Call reusable workflow directly at the job level
    uses: HaiderAli532/react-with-cicd/.github/workflows/include-npm-steps.yml@main
    with:
      node-version: ${{ matrix.node-version }}
