# .github/workflows/nodejs.yaml
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Reusable workflow call (if using workflow_call)
    - name: Call npm setup workflow
      uses: react-with-cicd/.github/workflows/include-npm-steps.yml@main
      with:
        node-version: ${{ matrix.node-version }}
