# .github/workflows/node-ci.yml
name: Node.js CI for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-node-basic-template:
    uses: ./.github/workflows/include-npm-steps.yml  # Call the reusable template
    with:
      node_version: '16'  # Optionally override the Node.js version
