name: Node.js CI (Reusable)

on:
  # Customize these events as needed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

inputs:
  node_version:
    description: 'Node.js version to use (e.g., 18.x, 20.x, 22.x)'
    required: true
  build_script:
    description: 'Script to build the project (e.g., npm run build)'
    default: 'npm run build --if-present'
  test_script:
    description: 'Script to run tests (e.g., npm test)'
    default: 'npm test'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: ${{ inputs.node_version }}  # Use input for flexibility

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'  # Enable npm cache

      - run: npm ci  # Install dependencies

      - name: Build
        run: ${{ inputs.build_script }}

      - name: Test
        run: ${{ inputs.test_script }}